[project]
name = "browserbase-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browserbase>=1.2.0",
    "playwright>=1.50.0",
    "python-dotenv>=1.0.1",
]
